name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup-msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: true
          install: >-
            msys2-devel
            base-devel
            asciidoc
            doxygen
            git
            meson
            ninja
            gettext-devel
            heimdal-devel
            libarchive-devel
            libcurl-devel
            libgpgme-devel
            libsqlite-devel
            libunistring-devel

      - name: Build
        shell: msys2 {0}
        run: |
          meson _build \
            --auto-features=enabled \
            --default-library=static \
            -Dbuildstatic=true \
            -Ddoxygen=enabled \
            -Dfile-seccomp=disabled

          meson compile -C _build

      - name: Install
        shell: msys2 {0}
        run: |
          DESTDIR="$(pwd)"/_dest meson install -C _build

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: install
          path: _dest/

  build-linux:
    runs-on: ubuntu-latest
    container: debian:bookworm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          apt update
          apt -y install --no-install-recommends \
            git pkg-config meson gcc libtool \
            libgpgme-dev libarchive-dev libcurl4-openssl-dev libssl-dev curl \
            gettext python3 python3-setuptools dash gawk ca-certificates \
            fakeroot fakechroot

      - name: Build
        run: |
          meson setup --buildtype=debug build
          ninja -C build
          fakechroot meson test -C build
